<?xml version="1.0" encoding="utf-8"?><Database Name="QLCHDT" Class="QLCHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-SLC41VO7;Initial Catalog=QLCHDT;Integrated Security=True" SettingsObjectName="LeQuocHung_BlackMobile.Properties.Settings" SettingsPropertyName="QLCHDTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="Sohoadon" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mahang" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Hinhthucthanhtoan" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="Sohoadon" OtherKey="Sohoadon" Type="HOADON" IsForeignKey="true" />
      <Association Name="MATHANG_CHITIETHOADON" Member="MATHANG" ThisKey="Mahang" OtherKey="Mahang" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="Sohoadon" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Makhachhang" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Manhanvien" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ngaymuahang" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="Sohoadon" OtherKey="Sohoadon" Type="CHITIETHOADON" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="Makhachhang" OtherKey="Makhachhang" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="Manhanvien" OtherKey="Manhanvien" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="Makhachhang" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenkhachhang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Dienthoai" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="Makhachhang" OtherKey="Makhachhang" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHANG" Member="LOAIHANGs">
    <Type Name="LOAIHANG">
      <Column Name="Maloaihang" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenloaihang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LOAIHANG_MATHANG" Member="MATHANGs" ThisKey="Maloaihang" OtherKey="Maloaihang" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.MATHANG" Member="MATHANGs">
    <Type Name="MATHANG">
      <Column Name="Mahang" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenhang" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Macongty" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Maloaihang" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Thoigianbaohanh" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Donvitinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Giahang" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Ngaynhaphang" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="MATHANG_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="Mahang" OtherKey="Mahang" Type="CHITIETHOADON" />
      <Association Name="LOAIHANG_MATHANG" Member="LOAIHANG" ThisKey="Maloaihang" OtherKey="Maloaihang" Type="LOAIHANG" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_MATHANG" Member="NHACUNGCAP" ThisKey="Macongty" OtherKey="Macongty" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="Macongty" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tencongty" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Dienthoai" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_MATHANG" Member="MATHANGs" ThisKey="Macongty" OtherKey="Macongty" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="Manhanvien" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tennhanvien" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Ngayvaolam" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Quequan" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Dienthoai" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Luongcoban" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Phucap" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="Manhanvien" OtherKey="Manhanvien" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tendangnhap" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Quanly" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>